### ISSUE TITLE
App without any visuals

### ISSUE THREAD

**Issue by eizanendoso** [Requarks/wiki-heroku#15]
Hi there, I've cloned the repo, committed the changes, and pushed to Heroku, in order to change the SSH settings, but ended up without any graphics/js:

![capture](https://user-images.githubusercontent.com/19331833/46728235-e9978100-ccb4-11e8-8883-7277c62ba0cc.PNG)

I used the 'Deply to Heroku' button but have not been able to get it to successfully authenticate with github, so downloaded the slug, made changes to SSH section of the config.yml file only to end up with the same result. Would be grateful for any help! Thanks!!

**Comment by NGPixel** [comment]
https://docs.requarks.io/wiki/install/troubleshooting#weird-display-no-styling-missing-css

**Comment by eizanendoso** [comment]
Thank you!
